apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-8zat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-8zat
    app.kubernetes.io/part-of: cin4s-839-0040-app
  name: devfile-sample-8zat
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-8zat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-8zat
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0040-tenant/cin4s-839-0040-app/devfile-sample-8zat@sha256:74499ced2968cdce85c795659e2b72275c874c5f658c399bc24df482a3a7aae7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
