apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8zat
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0040-tenant/cin4s-839-0040-app/devfile-sample-8zat@sha256:74499ced2968cdce85c795659e2b72275c874c5f658c399bc24df482a3a7aae7
        name: my-nodejs
        resources: {}
status: {}
